// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLWHvD0Uynjo4h_nRPkqONptxD1HK5Jxc',
    appId: '1:453160526913:web:9c05b2d084aa4847a5d2c0',
    messagingSenderId: '453160526913',
    projectId: 'bookstashammu',
    authDomain: 'bookstashammu.firebaseapp.com',
    storageBucket: 'bookstashammu.firebasestorage.app',
    measurementId: 'G-11P0068W1H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARLDjCH7wDpmnYln5LAHanfNYnSKkK5JM',
    appId: '1:453160526913:android:5bf3786b2a239a18a5d2c0',
    messagingSenderId: '453160526913',
    projectId: 'bookstashammu',
    storageBucket: 'bookstashammu.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCOGL8Ce25PwwqAv6142SabBe_RddT1cs',
    appId: '1:453160526913:ios:4cf5c814c6c3b723a5d2c0',
    messagingSenderId: '453160526913',
    projectId: 'bookstashammu',
    storageBucket: 'bookstashammu.firebasestorage.app',
    iosBundleId: 'com.example.bookStash',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCCOGL8Ce25PwwqAv6142SabBe_RddT1cs',
    appId: '1:453160526913:ios:4cf5c814c6c3b723a5d2c0',
    messagingSenderId: '453160526913',
    projectId: 'bookstashammu',
    storageBucket: 'bookstashammu.firebasestorage.app',
    iosBundleId: 'com.example.bookStash',
  );
}
